// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var buildings = Buildings.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Buildings
    {
        [JsonProperty("amenities")]
        public Amenities Amenities { get; set; }

        [JsonProperty("design")]
        public Amenities Design { get; set; }

        [JsonProperty("financial")]
        public Amenities Financial { get; set; }

        [JsonProperty("gallery")]
        public Amenities Gallery { get; set; }

        [JsonProperty("history")]
        public Amenities History { get; set; }

        [JsonProperty("location")]
        public Amenities Location { get; set; }

        [JsonProperty("neighborhood")]
        public Amenities Neighborhood { get; set; }

        [JsonProperty("notes")]
        public Amenities Notes { get; set; }

        [JsonProperty("occupants")]
        public Amenities Occupants { get; set; }

        [JsonProperty("overview")]
        public Amenities Overview { get; set; }

        [JsonProperty("purpose")]
        public Amenities Purpose { get; set; }
    }

    public partial class Amenities
    {
        [JsonProperty("attributes", NullValueHandling = NullValueHandling.Ignore)]
        public Attribute[] Attributes { get; set; }

        [JsonProperty("icon")]
        public string Icon { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("order")]
        public long Order { get; set; }
    }

    public partial class Attribute
    {
        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("field_type", NullValueHandling = NullValueHandling.Ignore)]
        public string FieldType { get; set; }

        [JsonProperty("description", NullValueHandling = NullValueHandling.Ignore)]
        public string Description { get; set; }
    }

    public partial class Buildings
    {
        public static Buildings FromJson(string json) => JsonConvert.DeserializeObject<Buildings>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Buildings self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
