// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var universes = Universes.FromJson(jsonString);

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class Universes
    {
        [JsonProperty("contributors")]
        public Contributors Contributors { get; set; }

        [JsonProperty("gallery")]
        public Contributors Gallery { get; set; }

        [JsonProperty("history")]
        public History History { get; set; }

        [JsonProperty("notes")]
        public History Notes { get; set; }

        [JsonProperty("overview")]
        public Overview Overview { get; set; }

        [JsonProperty("rules")]
        public History Rules { get; set; }
    }

    public partial class Contributors
    {
        [JsonProperty("icon")]
        public string Icon { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }
    }

    public partial class History
    {
        [JsonProperty("attributes")]
        public HistoryAttribute[] Attributes { get; set; }

        [JsonProperty("icon")]
        public string Icon { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }
    }

    public partial class HistoryAttribute
    {
        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class Overview
    {
        [JsonProperty("attributes")]
        public OverviewAttribute[] Attributes { get; set; }

        [JsonProperty("icon")]
        public string Icon { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }
    }

    public partial class OverviewAttribute
    {
        [JsonProperty("field_type", NullValueHandling = NullValueHandling.Ignore)]
        public string FieldType { get; set; }

        [JsonProperty("label")]
        public string Label { get; set; }

        [JsonProperty("name")]
        public string Name { get; set; }
    }

    public partial class Universes
    {
        public static Universes FromJson(string json) => JsonConvert.DeserializeObject<Universes>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this Universes self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
